### ISSUE TITLE
lorem ipsum

### ISSUE THREAD

**Issue by Tureyz** [Eteru/ELF-Detective#1]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eu varius ligula, fermentum tempus leo. Morbi auctor fermentum purus, vel aliquam purus malesuada vitae. Mauris tincidunt venenatis sapien non pretium. Nam ullamcorper mauris purus, commodo facilisis tellus feugiat quis. Donec pulvinar mauris quis faucibus volutpat. Maecenas dapibus nec quam eget luctus. Curabitur scelerisque congue commodo. Sed vulputate libero vitae orci vestibulum, in lacinia quam laoreet. Pellentesque bibendum mi eu risus consequat, eu congue lorem posuere. In a cursus ipsum, sit amet tempor neque. Cras eleifend non est a aliquet. Sed finibus eget risus id porta. Ut vitae arcu id risus molestie vehicula.

**Comment by Eteru** [comment]
Test issue. Closing it.
