### ISSUE TITLE
More objects at a time

### ISSUE THREAD

**Issue by gmuraru** [Eteru/ELF-Detective#2]
Currently, when I want to add a new object file the window would pop-up in _/home_ directory.
I would have to go to the working directory and add the object files one by one.

The frustrating part is that it would not remember last directory where I was if I want to add a new object file. I would have to go to the same working directory over and over again (until I added all object files).

There could be 2 solutions:
- The possibility to add more object files at once
- The possibility to remember the last working directory

**Comment by Eteru** [comment]
Fixed!

Added support for both solutions. Closing this issue.

Thanks.
