### ISSUE TITLE
Movement with Arrows

### ISSUE THREAD

**Issue by gmuraru** [Eteru/ELF-Detective#3]
If there are multiple data in the left column and one of them is clicked, it would be selected in the correspondent _object file_ from the [right column](http://swarm.cs.pub.ro/~gmuraru/elf_detective.png)

But this thing does not work if the arrows are used. [Here](http://swarm.cs.pub.ro/~gmuraru/elf_detective_arrow.png) I select a data and then try to select another using the down arrow, but the previous one is selected in the _object file_.

**Comment by Eteru** [comment]
Fixed!

Thanks for reporting this issue!
